/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ltnc.cuoiky.quanlykhupho.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ltnc.cuoiky.quanlykhupho.controller.HoDan;
import ltnc.cuoiky.quanlykhupho.controller.KhuPho;
import ltnc.cuoiky.quanlykhupho.controller.Nguoi;
import ltnc.cuoiky.quanlykhupho.model.HODAN;
import ltnc.cuoiky.quanlykhupho.model.KHUPHO;
import ltnc.cuoiky.quanlykhupho.model.NGUOI;

/**
 *
 * @author Darkmoon
 */
public class SuaKhuPhoJFrame extends javax.swing.JFrame {

    String maKhuPho;
    ArrayList<HODAN> danhSachHoDan;
    ArrayList<NGUOI> danhSachNguoi;
    int hoDanIndex = 0;
    int nguoiIndex = 0;

    /**
     * Creates new form SuaKhuPhoJFrame
     */
    public SuaKhuPhoJFrame(String maKhuPho, boolean isEdit) {
        initComponents();
        if (isEdit) {
            lblTieuDe.setText("Sửa khu phố");
        } else {
            lblTieuDe.setText("Xem khu phố");
        }
        txfHoTen.setEditable(isEdit);
        txfNamSinh.setEditable(isEdit);
        txfSoNha.setEditable(isEdit);
        txfTenKhuPho.setEditable(isEdit);
        txfTuoi.setEditable(isEdit);
        txfNgheNghiep.setEditable(isEdit);
        btnLuuHoDan.setVisible(isEdit);
        btnLuuNguoi.setVisible(isEdit);
        btnLuuKhuPho.setVisible(isEdit);

        this.maKhuPho = maKhuPho;
        loadKhuPho();
        loadHoDan();
        loadNguoi();

        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTieuDe = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLuuHoDan = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txfMaHoDan = new javax.swing.JTextField();
        txfSoNha = new javax.swing.JTextField();
        btnHoDanTruoc = new javax.swing.JButton();
        btnHoDanSau = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfMaKhuPho = new javax.swing.JTextField();
        txfTenKhuPho = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txfMaNguoi = new javax.swing.JTextField();
        txfHoTen = new javax.swing.JTextField();
        txfTuoi = new javax.swing.JTextField();
        txfNamSinh = new javax.swing.JTextField();
        txfNgheNghiep = new javax.swing.JTextField();
        btnLuuNguoi = new javax.swing.JButton();
        btnThanhVienTruoc = new javax.swing.JButton();
        btnThanhVienSau = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThanhVien = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnLuuKhuPho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTieuDe.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblTieuDe.setText("Title");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        btnLuuHoDan.setText("Lưu");
        btnLuuHoDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuHoDanActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Mã hộ dân");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Số nhà");

        txfMaHoDan.setEditable(false);

        btnHoDanTruoc.setText("Hộ dân trước");
        btnHoDanTruoc.setEnabled(false);
        btnHoDanTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoDanTruocActionPerformed(evt);
            }
        });

        btnHoDanSau.setText("Hộ dân sau");
        btnHoDanSau.setEnabled(false);
        btnHoDanSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoDanSauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuuHoDan)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4))
                            .addGap(65, 65, 65)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txfSoNha, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                                .addComponent(txfMaHoDan)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnHoDanTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(btnHoDanSau, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfMaHoDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfSoNha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLuuHoDan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHoDanTruoc)
                    .addComponent(btnHoDanSau))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mã khu phố");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Tên khu phố");

        txfMaKhuPho.setEditable(false);

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Mã người");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Họ và tên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Tuổi");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Năm sinh");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Nghề nghiệp");

        txfMaNguoi.setEditable(false);

        btnLuuNguoi.setText("Lưu");
        btnLuuNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuNguoiActionPerformed(evt);
            }
        });

        btnThanhVienTruoc.setText("Thành viên trước");
        btnThanhVienTruoc.setEnabled(false);
        btnThanhVienTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhVienTruocActionPerformed(evt);
            }
        });

        btnThanhVienSau.setText("Thành viên sau");
        btnThanhVienSau.setEnabled(false);
        btnThanhVienSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhVienSauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txfNamSinh)
                            .addComponent(txfNgheNghiep, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfMaNguoi)
                            .addComponent(txfHoTen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txfTuoi, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnThanhVienTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhVienSau, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLuuNguoi)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfMaNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txfNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txfNgheNghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLuuNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThanhVienTruoc)
                    .addComponent(btnThanhVienSau))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblThanhVien.setFillsViewportHeight(true);
        tblThanhVien.setShowHorizontalLines(false);
        tblThanhVien.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblThanhVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfTenKhuPho, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(txfMaKhuPho))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txfMaKhuPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txfTenKhuPho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLuuKhuPho.setBackground(new java.awt.Color(51, 255, 51));
        btnLuuKhuPho.setText("Lưu");
        btnLuuKhuPho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuKhuPhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(lblTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuKhuPho, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuuKhuPho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTieuDe))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhVienSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhVienSauActionPerformed
        nguoiIndex++;
        loadNguoi();
    }//GEN-LAST:event_btnThanhVienSauActionPerformed

    private void btnLuuNguoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuNguoiActionPerformed
        String maNguoi = txfMaNguoi.getText();
        String hoTen = txfHoTen.getText();
        int namSinh = Integer.parseInt(txfNamSinh.getText());
        int tuoi = Integer.parseInt(txfTuoi.getText());
        String ngheNghiep = txfNgheNghiep.getText();
        int affectedRow = Nguoi.edit(maNguoi, hoTen, tuoi, namSinh, ngheNghiep);
        switch (affectedRow) {
            case -1:
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình, hãy thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Mã người không tồn tại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin người thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadHoDan();
                loadTable();
                break;
        }
    }//GEN-LAST:event_btnLuuNguoiActionPerformed

    private void btnHoDanSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoDanSauActionPerformed
        hoDanIndex++;
        loadHoDan();
        nguoiIndex = 0;
        loadNguoi();
    }//GEN-LAST:event_btnHoDanSauActionPerformed

    private void btnLuuHoDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuHoDanActionPerformed
        String maHoDan = txfMaHoDan.getText();
        String soNha = txfSoNha.getText();
        int affectedRow = HoDan.edit(maHoDan, soNha);
        switch (affectedRow) {
            case -1:
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình, hãy thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Mã hộ dân không tồn tại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin hộ dân thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadKhuPho();
                break;
        }
    }//GEN-LAST:event_btnLuuHoDanActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        new QLKhuPhoJFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnThanhVienTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhVienTruocActionPerformed
        nguoiIndex--;
        loadNguoi();
    }//GEN-LAST:event_btnThanhVienTruocActionPerformed

    private void btnHoDanTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoDanTruocActionPerformed
        hoDanIndex--;
        loadHoDan();
        nguoiIndex = 0;
        loadNguoi();
    }//GEN-LAST:event_btnHoDanTruocActionPerformed

    private void btnLuuKhuPhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuKhuPhoActionPerformed
        String tenKhuPho = txfTenKhuPho.getText();
        int affectedRow = KhuPho.edit(maKhuPho, tenKhuPho);
        switch (affectedRow) {
            case -1:
                JOptionPane.showMessageDialog(this, "Có lỗi trong quá trình, hãy thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                break;
            case 0:
                JOptionPane.showMessageDialog(this, "Mã khu phố không tồn tại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(this, "Cập nhật thông tin khu phố thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                loadKhuPho();
                break;
        }
    }//GEN-LAST:event_btnLuuKhuPhoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHoDanSau;
    private javax.swing.JButton btnHoDanTruoc;
    private javax.swing.JButton btnLuuHoDan;
    private javax.swing.JButton btnLuuKhuPho;
    private javax.swing.JButton btnLuuNguoi;
    private javax.swing.JButton btnThanhVienSau;
    private javax.swing.JButton btnThanhVienTruoc;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JTable tblThanhVien;
    private javax.swing.JTextField txfHoTen;
    private javax.swing.JTextField txfMaHoDan;
    private javax.swing.JTextField txfMaKhuPho;
    private javax.swing.JTextField txfMaNguoi;
    private javax.swing.JTextField txfNamSinh;
    private javax.swing.JTextField txfNgheNghiep;
    private javax.swing.JTextField txfSoNha;
    private javax.swing.JTextField txfTenKhuPho;
    private javax.swing.JTextField txfTuoi;
    // End of variables declaration//GEN-END:variables

    private void loadKhuPho() {
        KHUPHO khuPho = KhuPho.getByMaKhuPho(maKhuPho);
        if (khuPho == null) {
            JOptionPane.showMessageDialog(this, "Mã khu phố không hợp lệ hoặc xảy ra lỗi, thử lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            new QLKhuPhoJFrame().setVisible(true);
            return;
        }
        txfMaKhuPho.setText(khuPho.getMaKhuPho());
        txfTenKhuPho.setText(khuPho.getTenKhuPho());
        danhSachHoDan = HoDan.getByMaKhuPho(khuPho.getMaKhuPho());
    }

    private void loadHoDan() {
        if (hoDanIndex < 0 || hoDanIndex >= danhSachHoDan.size()) {
            txfMaHoDan.setText("");
            txfSoNha.setText("");
            danhSachNguoi = new ArrayList<>();
        } else {
            HODAN hoDan = danhSachHoDan.get(hoDanIndex);
            txfMaHoDan.setText(hoDan.getMaHoDan());
            txfSoNha.setText(hoDan.getSoNha());
            danhSachNguoi = Nguoi.getByMaHoDan(hoDan.getMaHoDan());
        }
        if (hoDanIndex < danhSachHoDan.size() - 1) {
            btnHoDanSau.setEnabled(true);
        } else {
            btnHoDanSau.setEnabled(false);
        }
        if (hoDanIndex > 0) {
            btnHoDanTruoc.setEnabled(true);
        } else {
            btnHoDanTruoc.setEnabled(false);
        }
    }

    private void loadNguoi() {
        if (nguoiIndex < 0 || nguoiIndex >= danhSachNguoi.size()) {
            txfMaNguoi.setText("");
            txfHoTen.setText("");
            txfNamSinh.setText("");
            txfTuoi.setText("");
            txfNgheNghiep.setText("");
        } else {
            NGUOI nguoi = danhSachNguoi.get(nguoiIndex);
            txfMaNguoi.setText(nguoi.getMaNguoi());
            txfHoTen.setText(nguoi.getHoTen());
            txfNamSinh.setText(nguoi.getNamSinh() + "");
            txfTuoi.setText(nguoi.getTuoi() + "");
            txfNgheNghiep.setText(nguoi.getNgheNghiep());
        }
        if (nguoiIndex < danhSachNguoi.size() - 1) {
            btnThanhVienSau.setEnabled(true);
        } else {
            btnThanhVienSau.setEnabled(false);
        }
        if (nguoiIndex > 0) {
            btnThanhVienTruoc.setEnabled(true);
        } else {
            btnThanhVienTruoc.setEnabled(false);
        }
    }

    private void loadTable() {
        ArrayList<NGUOI> danhSach = Nguoi.getByMaKhuPho(maKhuPho);
        String[][] data = new String[danhSach.size()][6];
        for (int i = 0; i < danhSach.size(); i++) {
            data[i][0] = danhSach.get(i).getMaHoDan();
            data[i][1] = danhSach.get(i).getMaNguoi();
            data[i][2] = danhSach.get(i).getHoTen();
            data[i][3] = danhSach.get(i).getTuoi() + "";
            data[i][4] = danhSach.get(i).getNamSinh() + "";
            data[i][5] = danhSach.get(i).getNgheNghiep();
        }
        tblThanhVien.setModel(new DefaultTableModel(data, new String[]{"Mã hộ dân", "Mã người", "Họ tên", "Tuổi", "Năm sinh", "Nghề nghiệp"}));
        tblThanhVien.setTableHeader(null);
    }
}
